### ISSUE TITLE
Shows failed everytime

### ISSUE THREAD

**Issue by ankitmhatre** [ConteDevel/flutter-account-manager-plugin#1]
When I ran app for the first time and granted the permissions. It said failed. Also it doesn't update.
The future doesn't get past this line`20(main.dart).

`var accounts = await AccountManager.getAccounts();`

Also I am not able to create the account through settings.

**Comment by ghostman2013** [comment]
> When I ran app for the first time and granted the permissions. It said failed. Also it doesn't update.
> The future doesn't get past this line`20(main.dart).
> 
> `var accounts = await AccountManager.getAccounts();`
> 
> Also I am not able to create the account through settings.

Hello! Can you write which OS kind and version you met problem on? Now plugin works with Android only.

**Comment by ghostman2013** [comment]
> When I ran app for the first time and granted the permissions. It said failed. Also it doesn't update.
> The future doesn't get past this line`20(main.dart).
> 
> `var accounts = await AccountManager.getAccounts();`
> 
> Also I am not able to create the account through settings.

@ankitmhatre, I've updated **README.md** to provide more details about installation and using of our plug-in.

**Comment by ankitmhatre** [comment]
@ghostman2013 

Testing was done on a moto g(8)plus
Android version : 9.0
Android security patch : 1 April 2020

**Comment by ghostman2013** [comment]
> @ghostman2013
> 
> Testing was done on a moto g(8)plus
> Android version : 9.0
> Android security patch : 1 April 2020

Sorry, did you complete the tutorial from **README.md**? There is required to implement `AbstractAccountAuthenticator` and setup configuration to allow your app to manage accounts on Android device.

**Comment by ankitmhatre** [comment]
@ghostman2013  Yep I did, In fact I tried the example from the repository first.

**Comment by ghostman2013** [comment]
> @ghostman2013 Yep I did, In fact I tried the example from the repository first.

Thank you for feedback! I will check where the problem can be

**Comment by ghostman2013** [comment]
The error was fixed in new version of the plugin.
