### ISSUE TITLE
Next update

### ISSUE THREAD

**Issue by Vagharsh75** [ConteDevel/flutter-account-manager-plugin#13]
Hello there,
We use https://github.com/ConteDevel/flutter-account-manager-plugin library, which was last updated 11 months ago.
Please let us know whether you're going to have any updates in the near future.
Thanks in advance.

Best Regards,
Connectto Team

**Comment by ghostman2013** [comment]
> Hello there, We use https://github.com/ConteDevel/flutter-account-manager-plugin library, which was last updated 11 months ago. Please let us know whether you're going to have any updates in the near future. Thanks in advance.
> 
> Best Regards, Connectto Team

Hello, @Vagharsh75!

To be honest I was not sure it's still actual. Yap, I can update it this week up to the latest versions and maybe fix some problems

**Comment by Vagharsh75** [comment]
Hi Denis,

Yeah, it will be a great help for us. We'll be waiting for your update.
Thank you.

Regards,
Connectto Team

ср, 17 авг. 2022 г., 17:34 Denis Sologub ***@***.***>:

**Comment by Vagharsh75** [comment]
Hi Denis,

I just wonder whether you have any updates.

Regards,
Connectto Team

ср, 17 авг. 2022 г. в 17:42, Вагарш Акопян ***@***.***>:

**Comment by ghostman2013** [comment]
> Hi Denis, I just wonder whether you have any updates. Regards, Connectto Team ср, 17 авг. 2022 г. в 17:42, Вагарш Акопян ***@***.***>:
> […](#)

Hi, Vagharsh75!

Sorry, I didn't forget about the update, I was working on weekends, so I hadn't just time for it. 

I begun to work on a new version in background, I only have time in the evenings now, unfortunately. I suppose it will be ready at these weekends.

Sincerely, 
Denis Sologub

**Comment by Vagharsh75** [comment]
Hi Denis,

No worries, thanks for the response. I'll be waiting for it.

Regards,
Vagharsh




пт, 26 авг. 2022 г. в 01:25, Denis Sologub ***@***.***>:

**Comment by ghostman2013** [comment]
> Hi Denis, No worries, thanks for the response. I'll be waiting for it. Regards, Vagharsh пт, 26 авг. 2022 г. в 01:25, Denis Sologub ***@***.***>:
> […](#)

I've posted a new package version, there are no new features but some updates of platform versions and deps.

**Comment by Vagharsh75** [comment]
Hi Denis,

Thank you a lot. Awesome job.

Regards,
Vagharsh

пт, 2 сент. 2022 г., 02:12 Denis Sologub ***@***.***>:
