### ISSUE TITLE
Account removed on app uninstall

### ISSUE THREAD

**Issue by chrisbin-kutuki** [ConteDevel/flutter-account-manager-plugin#15]
Hello there,
The added accounts are being removed on app uninstall. Is this the expected behaviour? I wanted the user account to persist even after the app is uninstalled. 

Thankyou

**Comment by ghostman2013** [comment]
> Hello there, The added accounts are being removed on app uninstall. Is this the expected behaviour? I wanted the user account to persist even after the app is uninstalled.
> 
> Thankyou

Hello! 

As I know, Android and iOS allow to achieve such behaviour by using backup/sync subsystem only.
