### ISSUE TITLE
Contacts permission on Android 6.0+

### ISSUE THREAD

**Issue by bostrot** [ConteDevel/flutter-account-manager-plugin#5]
I do not see a reason why you would need contacts permission on Android 6.0+. I can't find anything about that in the [android docs](https://developer.android.com/training/id-auth) either. Could you elaborate what these permissions are for?

It works fine without those permissions on Android 10 at least.

**Comment by ghostman2013** [comment]
> I do not see a reason why you would need contacts permission on Android 6.0+. I can't find anything about that in the [android docs](https://developer.android.com/training/id-auth) either. Could you elaborate what these permissions are for?
> 
> It works fine without those permissions on Android 10 at least.

Hello!

You will need to request `contact` permissions if your app needs to read accounts that was added by other apps. Our plugin doesn't require it, we will fix docs in next versions.
